CREATE TABLE eventos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    titulo VARCHAR(200) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    descricao TEXT,
    resumo VARCHAR(500),
    banner VARCHAR(255),
    imagem VARCHAR(255),
    data_inicio DATETIME NOT NULL,
    data_fim DATETIME,
    local VARCHAR(200),
    endereco VARCHAR(255),
    cidade VARCHAR(100),
    estado CHAR(2),
    cep VARCHAR(10),
    latitude DECIMAL(10, 8),
    longitude DECIMAL(11, 8),
    vagas INT DEFAULT 0,
    inscritos INT DEFAULT 0,
    valor DECIMAL(10, 2) DEFAULT 0,
    certificado TINYINT(1) DEFAULT 1,
    publicado TINYINT(1) DEFAULT 1,
    destaque TINYINT(1) DEFAULT 0,
    cor VARCHAR(10) DEFAULT '#0d6efd',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);